language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
  - pip install codecov
services: mongodb
before_install:
  - pip install codecov
after_success:
  - codecov
notifications:
  slack: eecr:6jvPRxT579QoiP7YW28iMc3V
